easy_admin:
    design:
        assets:
            css:
                - 'assets/css/app.css'
            js:
                - 'assets/js/app.js'
        menu:
            - label: 'Données de base'
              icon: 'box-open'
              children:
                - {entity: 'PosteTravail', icon: 'inbox', label: 'Poste de travail'}
                - {entity: 'Activite',icon: 'inbox', label: 'Activité'}
                - {entity: 'Operation',icon: 'inbox', label: 'Opération'}
            - label: 'Naviquiz'
              icon: 'question-circle'
              children:
                - {entity: 'Reponse', icon: 'inbox', label: 'Réponse'}
                - {entity: 'Question',icon: 'inbox', label: 'Question'}
            - label: 'Configurateur'
              icon: 'cogs'
              children:
                - {entity: 'GammeEnveloppe', icon: 'inbox', label: 'Gamme enveloppe'}
                - {entity: 'Regle',icon: 'inbox', label: 'Règle'}
    entities:
#        # List the entity class name you want to manage
        - App\Entity\PosteTravail
        - App\Entity\Activite
        - App\Entity\Question
        - App\Entity\Reponse
        - App\Entity\GammeEnveloppe
        - App\Entity\Regle
        - App\Entity\Operation
        - App\Entity\Gamme

    site_name: 'Cadrans Fluckiger SA - Back-office'
