easy_admin:
    design:
        menu:
            - label: 'Données de base'
              icon: 'box-open'
              children:
                - {entity: 'Departement', icon: 'inbox'}
                - {entity: 'CentreProduction', icon: 'inbox'}
                - {entity: 'PosteTravail', icon: 'inbox'}
                - {entity: 'Activite', icon: 'inbox'}
                - {entity: 'Operation', icon: 'inbox'}

            - label: 'Naviquiz'
              icon: 'question-circle'
              children:
                - {entity: 'Question',icon: 'inbox', label: 'Question'}
                - {entity: 'Reponse', icon: 'inbox', label: 'Réponse'}

            - label: 'Configurateur'
              icon: 'cogs'
              children:
                - {entity: 'GammeEnveloppe', icon: 'inbox', label: 'Gamme enveloppe'}
                - {entity: 'Regle',icon: 'inbox', label: 'Règle'}
            - { label: 'Naviquiz', route: 'config_naviquiz', icon: 'tree' }
            - label: 'Imports données'
              icon: 'cloud-upload-alt'
              children:
                - {label: 'Import données',icon: 'inbox', route: 'import_data'}
                - {label: 'Import liens',icon: 'inbox', route: 'import_link'}

            - label: 'Export données'
              icon: 'cloud-download-alt'
              children:
                - {label: 'Export structure',icon: 'inbox', route: 'export_structure'}
                - {label: 'Export GE',icon: 'inbox', route: 'export_ge'}

    entities:
#        # List the entity class name you want to manage
        Reponse:
            class: App\Entity\Reponse
            label: 'Réponse'
            list:
                fields:
                    - { property: 'img', type: 'image', base_path: '%app.path.reponse_images%' }
                    - { property: 'short', label: 'Réponse courte'}
                    - { property: 'information', label: 'Information'}
                    - { property: 'gammeEnveloppe', label: "Gamme enveloppe"}

            form:
                fields:
                    - { property: 'short', label: 'Réponse courte' }
                    - { property: 'information', label: 'Information' }
                    - { property: 'imageFile', type: 'file', label: 'Image de la réponse' }
                    - { property: 'gammeEnveloppe', label: "Gamme enveloppe"}

        PosteTravail:
            class: App\Entity\PosteTravail
            label: 'Poste de travail'
            list:
                fields:
                    - { property: 'reference', label: 'Référence'}
                    - { property: 'description', label: 'Description' }
                    - { property: 'activites', label: "Activités" }
            form:
                fields:
                    - { property: 'reference', label: 'Référence'}
                    - { property: 'description', label: 'Description' }
                    - { property: 'activites', type_options: { by_reference: false } }
            
        Activite:
            class: App\Entity\Activite
            label: 'Activité'
            list:
                fields:
                    - { property: 'reference', label: 'Référence'}
                    - { property: 'description', label: 'Description' }
                    - { property: 'pdts', label: 'Poste de travail' }

            
        Question:
            class: App\Entity\Question
            label: 'Question'
            list:
                fields:
                    - { property: 'short', label: 'Question courte'}
                    - { property: 'q_long', label: 'Question longue' }
                    - { property: 'information', label: 'Information'}

            form:
                fields:
                    - { property: 'short', label: 'Question courte' }
                    - { property: 'q_long', label: 'Question longue' }
                    - { property: 'information', label: 'Information'}

        GammeEnveloppe:
            class: App\Entity\GammeEnveloppe
            label: 'Gamme enveloppe'
            list:
                actions:
                    - { name: 'configGE', icon: 'cubes', label: 'Mise à jour' }
                fields:
                    - { property: 'nom', label: 'Titre' }
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'gammes', label: 'Gammes'}
                    - { property: 'gammes', label: 'Opérations'}
                    - { property: 'gammes', label: 'Réponses'}

            controller: App\Controller\AdminController
            form:
                fields:
                    - { property: 'nom', label: 'Titre' }
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'gammes', label: 'Gammes'}

        Regle:
            class: App\Entity\Regle
            label: 'Règle'
            list:
                fields:
                    - { property: 'question', label: 'Question' }
                    - { property: 'aide', label: 'Aide' }
                    - { property: 'linkRegleOperations', label: 'Liens avec des opérations'}
            form:
                fields:
                    - { property: 'question', label: 'Question' }
                    - { property: 'aide', label: 'Aide' }
             
        Operation:
            class: App\Entity\Operation
            label: 'Opération'
            list:
                fields:
                    - { property: 'numero', label: 'Numéro' }
                    - { property: 'pdt', label: 'Poste de travail' }
                    - { property: 'activite', label: 'Activité'}
                    - { property: 'linkregleoperation', label: 'Lien avec les règles'}

        CentreProduction:
            class: App\Entity\CentreProduction
            label: 'Centre de production'
            list:
                fields:
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'designation', label: 'Désignation' }
                    - { property: 'cout', label: 'Coût'}
                    - { property: 'pdts', label: 'Poste de travail'}
            form:
                fields:
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'designation', label: 'Désignation' }
                    - { property: 'cout', label: 'Coût'}
                    - { property: 'pdts', label: 'Poste de travail', type_options: { by_reference: false }}

        Departement:
            class: App\Entity\Departement
            label: 'Département'
            list:
                fields:
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'designation', label: 'Désignation' }
                    - { property: 'centreproductions', label: 'Centre de productions'}
            form:
                fields:
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'designation', label: 'Désignation' }
                    - { property: 'centreproductions', label: 'Centre de productions', type_options: { by_reference: false }}

        Gamme:
            class: App\Entity\Gamme
            label: 'Gamme'


    site_name: '<a href="https://naviquiz.repliqa.fr">Cadrans Fluckiger SA - Back-office</a>'
