easy_admin:
    design:
        assets:
            css:
                - 'assets/css/app.css'
            js:
                - 'assets/js/app.js'
        menu:
            - label: 'Données de base'
              icon: 'box-open'
              children:
                - {entity: 'PosteTravail', icon: 'inbox', label: 'Poste de travail'}
                - {entity: 'Activite',icon: 'inbox', label: 'Activité'}
                - {entity: 'Operation',icon: 'inbox', label: 'Opération'}
            - label: 'Naviquiz'
              icon: 'question-circle'
              children:
                - {entity: 'Reponse', icon: 'inbox', label: 'Réponse'}
                - {entity: 'Question',icon: 'inbox', label: 'Question'}
            - label: 'Configurateur'
              icon: 'cogs'
              children:
                - {entity: 'GammeEnveloppe', icon: 'inbox', label: 'Gamme enveloppe'}
                - {entity: 'Regle',icon: 'inbox', label: 'Règle'}
    entities:
#        # List the entity class name you want to manage
        Reponse:
            class: App\Entity\Reponse
            label: 'Réponse'
            list:
                fields:
                    - { property: 'img', type: 'image', label: 'Image' }
                    - { property: 'short', label: 'Réponse courte'}
                    - { property: 'information', label: 'Information'}

        PosteTravail:
            class: App\Entity\PosteTravail
            label: 'Poste de travail'
            list:
                fields:
                    - { property: 'short', label: 'Question courte'}
                    - { property: 'q_long', label: 'Question longue' }
                    - { property: 'information', label: 'Information'}
            
        Activite:
            class: App\Entity\Activite
            label: 'Activité'
            
        Question:
            class: App\Entity\Question
            label: 'Question'
            list:
                fields:
                    - { property: 'short', label: 'Question courte'}
                    - { property: 'q_long', label: 'Question longue' }
                    - { property: 'information', label: 'Information'}

        GammeEnveloppe:
            class: App\Entity\GammeEnveloppe
            label: 'Gamme enveloppe'
            
        Regle:
            class: App\Entity\Regle
            label: 'Règle'
             
        Operation:
            class: App\Entity\Operation
            label: 'Opération'
                    
        Gamme:
            class: App\Entity\Gamme
            label: 'Gamme'


    site_name: 'Cadrans Fluckiger SA - Back-office'
