easy_admin:
    user:
        # this method/property must return the string representation of the user
        # (Symfony will look for getFullName(), isFullName(), ..., and 'fullName' property)
        name_property_path: 'fullName'
    design:
        menu:
            - label: 'Données PROD'
              icon: 'project-diagram'
              children:
                - {entity: 'Departement', icon: 'inbox'}
                - {entity: 'CentreProduction', icon: 'inbox'}
                - {entity: 'PosteTravail', icon: 'inbox'}
                - {entity: 'Activite', icon: 'inbox'}
                - {entity: 'ActivitePosteTravail', icon: 'inbox'}

            - label: 'Données PROTO'
              icon: 'box-open'
              children:
                 - {entity: 'PosteTravailProto', icon: 'inbox'}
                 - {entity: 'ActiviteProto', icon: 'inbox'}

            - label: 'Naviquiz'
              icon: 'question-circle'
              children:
                - {entity: 'Question',icon: 'inbox', label: 'Question'}
                - {entity: 'Reponse', icon: 'inbox', label: 'Réponse'}
                - {label: 'Structure', route: 'config_naviquiz', icon: 'tree' }

            - label: 'Enveloppe'
              icon: 'envelope'
              children:
                - {entity: 'ProcessusEnveloppe', icon: 'inbox', label: 'Processus enveloppe'}
                - {entity: 'GammeEnveloppe', icon: 'inbox', label: 'Gamme enveloppe'}
                - {entity: 'Regle',icon: 'inbox', label: 'Règle'}
            - label: 'Import données'
              icon: 'cloud-upload-alt'
              children:
                - { label: 'Données PROD',icon: 'inbox', route: 'import_data'}
                - { label: 'PDT PROTO',icon: 'inbox', route: 'import_data_pdt_proto'}

            - label: 'Export données'
              icon: 'cloud-download-alt'
              children:
                - {label: 'Export structure',icon: 'inbox', route: 'export_structure'}
                - {label: 'Export GE',icon: 'inbox', route: 'configurateur_index'}
            - label: 'Tables configuration'
              icon: 'table'
              children:
                - {entity: 'Unite', label: 'Unité', icon: 'inbox'}
            - {entity: 'User', icon: 'users', permission: 'ROLE_ADMIN'}



    entities:
        ProcessusEnveloppe:
            class: App\Entity\ProcessusEnveloppe
            label: 'Processus Enveloppe'
            actions:
                    - { name: 'linkGE', icon: 'cubes', label: 'Lier GE' }
            list:
                fields:
                    - { property: 'nom', label: 'Nom'}
                    - { property: 'processusEnveloppeGammeEnveloppes', label: 'GE lié(s)' }
            form:
                fields:
                    - { property: 'nom', label: 'Nom'}
                    - { property: 'processusEnveloppeGammeEnveloppes', label: 'GE lié(s)' }


        Reponse:
            class: App\Entity\Reponse
            label: 'Réponse'
            list:
                fields:
                    - { property: 'img', type: 'image', base_path: '%app.path.reponse_images%' }
                    - { property: 'short', label: 'Réponse courte'}
                    - { property: 'information', label: 'Information'}
                    - { property: 'gammeEnveloppe', label: "Gamme enveloppe"}

            form:
                fields:
                    - { property: 'short', label: 'Réponse courte' }
                    - { property: 'information', label: 'Information' }
                    - { property: 'imageFile', type: 'file', label: 'Image de la réponse' }
                    - { property: 'gammeEnveloppe', label: "Gamme enveloppe"}

        PosteTravail:
            class: App\Entity\PosteTravail
            label: 'Poste de travail'
            list:
                filters: [{ property: 'activitePosteTravails', type: 'App\Form\Filter\PosteTravailActivitePosteTravailFilterType', useOutputWalkers: true }]
                fields:
                    - { property: 'reference', label: 'Référence'}
                    - { property: 'description', label: 'Description' }
                    - { property: 'activitePosteTravails', label: "Activité-PDT lié" }
            form:
                fields:
                    - { property: 'reference', label: 'Référence'}
                    - { property: 'description', label: 'Description' }
                    - { property: 'activitePosteTravails', label: "Activité-PDT lié" }

        PosteTravailProto:
            class: App\Entity\PosteTravailProto
            label: 'Poste de travail Prototype'
            list:
                fields:
                    - { property: 'reference', label: 'Référence'}
                    - { property: 'description', label: 'Description' }
                    - { property: 'pdt', label: "Poste de Travail PROD lié" }
            form:
                fields:
                    - { property: 'reference', label: 'Référence'}
                    - { property: 'description', label: 'Description' }
                    - { property: 'pdt', label: "Poste de Travail PROD lié" }


        ActiviteProto:
            class: App\Entity\ActiviteProto
            label: 'Activité Prototype'
            list:
                fields:
                    - { property: 'reference', label: 'Référence'}
                    - { property: 'description', label: 'Description' }
                    - { property: 'activite', label: "Activité PROD liée" }
            form:
                fields:
                    - { property: 'reference', label: 'Référence'}
                    - { property: 'description', label: 'Description' }
                    - { property: 'activite', label: "Activité PROD liée" }
        Activite:
            class: App\Entity\Activite
            label: 'Activité'
            list:
                filters: [{ property: 'activitePosteTravails', type: 'App\Form\Filter\ActiviteActivitePosteTravailFilterType', useOutputWalkers: true }]
                fields:
                    - { property: 'reference', label: 'Référence'}
                    - { property: 'description', label: 'Description' }
                    - { property: 'activitePosteTravails', label: "Activité-PDT lié" }
            form:
                fields:
                    - { property: 'reference', label: 'Référence'}
                    - { property: 'description', label: 'Description' }
                    - { property: 'activitePosteTravails', label: "Activité-PDT lié" }

        ActivitePosteTravail:
            class: App\Entity\ActivitePosteTravail
            label: 'Activité-Poste de Travail'
            templates:
                edit: 'admin/customizations/activitePosteTravail_edit.html.twig'
                new: 'admin/customizations/activitePosteTravail_edit.html.twig'
            list:
                filters: [{ property: 'posteTravail' }, { property: 'activite' }]
                fields:
                    - { property: 'posteTravail', label: 'Poste de Travail'}
                    - { property: 'activite', label: 'Activité' }
            search:
                  fields: ['posteTravail.reference', 'posteTravail.description', 'activite.reference', 'activite.description']
            form:
                fields:
                    - { property: 'posteTravail', label: 'Poste de Travail'}
                    - { property: 'activite', label: 'Activité' }
                    - { property: 'time', type: 'App\Form\ActivitePosteTravailTimeType' }
        Time:
            class: App\Entity\Time
            label: 'Temps'

            form:
                fields:
                     - { property: 'unite'}

        Unite:
            class: App\Entity\Unite
            label: 'Unite'
            list:
                fields:
                     - { property: 'name', label: 'Nom' }
                     - { property: 'short', label: 'Désignation courte' }
            form:
                fields:
                     - { property: 'name', label: 'Nom' }
                     - { property: 'short', label: 'Désignation courte' }

        Question:
            class: App\Entity\Question
            label: 'Question'
            list:
                fields:
                    - { property: 'short', label: 'Question courte'}
                    - { property: 'q_long', label: 'Question longue' }
                    - { property: 'information', label: 'Information'}

            form:
                fields:
                    - { property: 'short', label: 'Question courte' }
                    - { property: 'q_long', label: 'Question longue' }
                    - { property: 'information', label: 'Information'}

        GammeEnveloppe:
            class: App\Entity\GammeEnveloppe
            label: 'Gamme enveloppe'
            list:
                actions:
                    - { name: 'configGE', icon: 'cubes', label: 'Séquence' }
                fields:
                    - { property: 'nom', label: 'Titre' }
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'regles', label: 'Règles'}
                    - { property: 'operations', label: 'Opérations'}
                    - { property: 'reponses', label: 'Réponses'}

            controller: App\Controller\AdminController
            form:
                fields:
                    - { property: 'nom', label: 'Titre' }
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'gammes', label: 'Gammes'}

        Regle:
            class: App\Entity\Regle
            label: 'Règle'
            list:
                fields:
                    - { property: 'question', label: 'Question' }
                    - { property: 'aide', label: 'Aide' }
                    - { property: 'linkRegleOperations', label: 'Liens avec des opérations'}
                    - { property: 'ge', label: 'GE lié'}
            form:
                fields:
                    - { property: 'question', label: 'Question' }
                    - { property: 'aide', label: 'Aide' }
                    - { property: 'ge', label: 'GE lié'}
             
        Operation:
            class: App\Entity\Operation
            label: 'Opération'
            list:
                fields:
                    - { property: 'numero', label: 'Numéro' }
                    - { property: 'pdt', label: 'Poste de travail' }
                    - { property: 'activite', label: 'Activité'}
                    - { property: 'linkregleoperation', label: 'Lien avec les règles'}

        CentreProduction:
            class: App\Entity\CentreProduction
            label: 'Centre de production'
            list:
                fields:
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'designation', label: 'Désignation' }
                    - { property: 'cout', label: 'Coût'}
                    - { property: 'pdts', label: 'Poste de travail'}
            form:
                fields:
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'designation', label: 'Désignation' }
                    - { property: 'cout', label: 'Coût'}
                    - { property: 'pdts', label: 'Poste de travail', type_options: { by_reference: false }}

        Departement:
            class: App\Entity\Departement
            label: 'Département'
            list:
                fields:
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'designation', label: 'Désignation' }
                    - { property: 'centreproductions', label: 'Centre de productions'}
            form:
                fields:
                    - { property: 'reference', label: 'Référence' }
                    - { property: 'designation', label: 'Désignation' }
                    - { property: 'centreproductions', label: 'Centre de productions', type_options: { by_reference: false }}

        Gamme:
            class: App\Entity\Gamme
            label: 'Gamme'

        User:
            class: App\Entity\User
            password_encoding: { algorithm: 'auto' }
            label: 'Utilisateur'
            list:
                actions:
                    - { name: 'edit'}
                fields:
                    - { property: 'email', label: 'Email' }
                    - { property: 'roles', label: 'Roles' }
            new:
                fields:
                    - { type: 'section', label: 'Informations obligatoires' }
                    - { property: 'email', label: 'Email' }
                    - { property : 'alias', label: 'Alias' }
                    - { property: 'plainPassword', label: 'Mot de passe (Si vide : Patek1839)', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_LECTEUR': 'ROLE_LECTEUR','ROLE_MODIFICATEUR': 'ROLE_MODIFICATEUR', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                    - { type: 'section', label: 'Informations complémentaire' }
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'birthday', label: 'Date de naissance', type_options: { widget: 'single_text', 'format': 'dd/MM/yyyy', 'attr': {'class': 'js-datepicker'} } }
            edit:
                fields:
                    - { type: 'section', label: 'Informations obligatoires' }
                    - { property: 'email', label: 'Email' }
                    - { property : 'alias', label: 'Alias' }
                    - { property: 'plainPassword', label: 'Mot de passe (Si vide, mot de passe inchangé)', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_LECTEUR': 'ROLE_LECTEUR','ROLE_MODIFICATEUR': 'ROLE_MODIFICATEUR', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                    - { type: 'section', label: 'Informations complémentaire' }
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'birthday', label: 'Date de naissance',  type_options: { widget: 'single_text', 'format': 'dd/MM/yyyy', 'attr': {'class': 'js-datepicker'} } }

    site_name: '<a href="https://cfsa.repliqa.fr">Cadrans Fluckiger SA - Back-office</a>'
