vich_uploader:
    db_driver: orm

    mappings:
        reponse_images:
            uri_prefix: '%app.path.reponse_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.reponse_images%'
            namer: vich_uploader.namer_uniqid